name:  自动化

on:
  schedule:
    - cron: '2 23,5,11 * * *'
  workflow_dispatch:  

jobs:
  job1:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python program
        run: python 曾瑞彬循环.py
  job2:

          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run Python program
              run: python 卢俊豪循环.py
